In [1]:
import numpy as np

array = np.array([2, 4, 6, 8, 10])
print(array)

[ 2  4  6  8 10]


In [2]:
print(array.dtype)

int32


In [3]:
import numpy as np

array = np.array([2, 4, 6, 8., 10])
print(array)
print(array.dtype)

[ 2.  4.  6.  8. 10.]
float64


In [4]:
import numpy as np

range_array = np.arange(1,51)
print(range_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [5]:
range_array2 = np.arange(1,51,3)
print(range_array2)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


In [6]:
import numpy as np
two_lists = [[2,4,6,8],[3,6,9,12]]
print(two_lists)

[[2, 4, 6, 8], [3, 6, 9, 12]]


In [7]:
for i in range(len(two_lists)):
    print(two_lists[i])

[2, 4, 6, 8]
[3, 6, 9, 12]


In [8]:
for i in range(len(two_lists)):
    print(two_lists[i])
    for j in range(len(two_lists[i])):
        print(two_lists[i][j])

[2, 4, 6, 8]
2
4
6
8
[3, 6, 9, 12]
3
6
9
12


In [9]:
two_lists_array = np.array(two_lists)
print(two_lists_array)

[[ 2  4  6  8]
 [ 3  6  9 12]]


In [10]:
for i in range(len(two_lists_array)):
    print(two_lists_array[i])
    for j in range(len(two_lists_array[i])):
        print(two_lists_array[i][j])

[2 4 6 8]
2
4
6
8
[ 3  6  9 12]
3
6
9
12


In [11]:
import numpy as np

array = np.zeros((5,4))
print("Original Array:", array, sep = "\n")

array[1][0] = 7
array[1][1] = 8
array[1][2] = 9

array[2][0] = 4
array[2][1] = 5
array[2][2] = 6

array[3][0] = 1
array[3][1] = 2
array[3][2] = 3

print("Updated Array:", array, sep = "\n")

Original Array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Updated Array:
[[0. 0. 0. 0.]
 [7. 8. 9. 0.]
 [4. 5. 6. 0.]
 [1. 2. 3. 0.]
 [0. 0. 0. 0.]]


In [12]:
zero_list = [[0,0,0],[0,0,0],[0,0,0]]
np.array(zero_list)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [13]:
Numpad = [["NumLock","/","*","-"],[7,8,9,"+"],[4,5,6,"="],[1,2,3,"Enter"],[0,",",".","Enter"]]
np.array(Numpad)

array([['NumLock', '/', '*', '-'],
       ['7', '8', '9', '+'],
       ['4', '5', '6', '='],
       ['1', '2', '3', 'Enter'],
       ['0', ',', '.', 'Enter']], dtype='<U11')

In [14]:
Numpad[1][1] = "9"
np.array(Numpad)

array([['NumLock', '/', '*', '-'],
       ['7', '9', '9', '+'],
       ['4', '5', '6', '='],
       ['1', '2', '3', 'Enter'],
       ['0', ',', '.', 'Enter']], dtype='<U11')

In [15]:
##I originally thought he said "Locking Data" and was super confused

NormalList = [[1,2,3],[4,5,6],[7,8,9]]

np.log(NormalList)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [16]:
np.log10(NormalList)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [17]:
np.log2(NormalList)

array([[0.        , 1.        , 1.5849625 ],
       [2.        , 2.32192809, 2.5849625 ],
       [2.80735492, 3.        , 3.169925  ]])

In [18]:
np.array(NormalList)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
for i in range(1000,10,-10):
    print(i, np.log10(i))

1000 3.0
990 2.99563519459755
980 2.9912260756924947
970 2.9867717342662448
960 2.9822712330395684
950 2.9777236052888476
940 2.9731278535996988
930 2.9684829485539352
920 2.963787827345555
910 2.9590413923210934
900 2.9542425094393248
890 2.949390006644913
880 2.9444826721501687
870 2.9395192526186187
860 2.934498451243568
850 2.929418925714293
840 2.9242792860618816
830 2.9190780923760737
820 2.9138138523837167
810 2.90848501887865
800 2.9030899869919438
790 2.8976270912904414
780 2.8920946026904804
770 2.886490725172482
760 2.8808135922807914
750 2.8750612633917
740 2.8692317197309762
730 2.863322860120456
720 2.8573324964312685
710 2.8512583487190755
700 2.845098040014257
690 2.838849090737255
680 2.832508912706236
670 2.8260748027008264
660 2.8195439355418688
650 2.8129133566428557
640 2.806179973983887
630 2.7993405494535817
620 2.792391689498254
610 2.785329835010767
600 2.7781512503836434
590 2.7708520116421442
580 2.7634279935629373
570 2.7558748556724915
560 2.748188027006200